### ISSUE TITLE
Two-value padding for forms

### ISSUE THREAD

**Issue by luigigorlero** [ptkio/directus-extension-theme-clean-compact-light#1]
The form → field → input → padding value defines the CSS variable `--theme--form--field--input--padding`. Since it is used across the app, having a two-value variable will break any CSS `calc()`. Suggesting having a smaller (but single) value, like `8px`.

**Comment by ptkio** [comment]
Thanks! I will see more about that.

**Comment by ptkio** [comment]
After testing, I've set it to 10px, and everything looks good now. Thank you for pointing out this issue. If you encounter any other issues or have any ideas, please feel free to share. I'm always open to feedback. :)

**Comment by luigigorlero** [comment]
I was also testing locally and it seemed inputs and forms looked just as good with a single value padding, thank you! I’m using this daily so I’ll be happy to report any visual discrepancy that I find (and maybe open a few PRs).

`--content-padding:0 32px!important;` in `style.scss` might need a revision too for the same reasons; I haven’t found an example where CSS broke because of it but all layout pagination has no bottom spacing (could be your design decision, tho) :)

![Screenshot 2024-03-14 alle 11 15 46](https://github.com/ptkio/directus-extension-theme-clean-compact-light/assets/22613842/be906538-45d0-4d00-95b3-8a7d48580b83)

**Comment by ptkio** [comment]
I see that; it appears when pagination is on a card layout. I will fix it and check all layouts.

I'm also glad to hear that you like the theme enough to use it daily. It motivates me even more to improve it !

**Comment by ptkio** [comment]
We have also fixed the pagination issue. Thanks.
